In [27]:
using PyPlot
using CSV
using PyCall
using JLD, HDF5

include("mg-fld.jl")

Estep

In [57]:
E1 = zeros(15).+a
T = zeros(15).+1;

In [58]:
B1(E1,T)/(a*c/(4*pi))

15-element Array{Float64,1}:
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566
 0.999999868114566

In [59]:
DB1DT(E1,T)/(4*a*c/(4*pi))

15-element Array{Float64,1}:
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563
 0.9999999668586563

In [104]:
Ts = reshape([1,2,3,4.0],2,2)
DBgDT(1e-6,1e6,Ts) ./(4*a*c*Ts.^3/4/pi)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [41]:
imag(B1(1e-6,1+1e-6*im))/1e-6

5.1761888380891004e-23

In [40]:
imag(B1(1e-6,1+1e-3*im))/1e-3

5.1811174602921323e-23

In [42]:
DB1DT(1e-6,1)

1.310076146924497

In [46]:
B1(1e-6,[1.,2,3])

MethodError: MethodError: no method matching exp(::LinearAlgebra.Transpose{Float64,Array{Float64,1}})
Closest candidates are:
  exp(!Matched::BigFloat) at mpfr.jl:558
  exp(!Matched::Missing) at math.jl:1070
  exp(!Matched::Complex{Float16}) at math.jl:1019
  ...